# Generated by Django 3.2.8 on 2021-11-28 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('harga', models.IntegerField()),
                ('gambar', models.FileField(upload_to='static/uploaded')),
                ('kategori', models.CharField(max_length=30)),
                ('info', models.TextField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCartModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('total_furnitur', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('notes', models.CharField(max_length=200)),
                ('futniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.furnituremodels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.TextField(null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('full_name', models.TextField(null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('birth_date', models.DateField(auto_now_add=True)),
                ('profile_pic', models.FileField(default='static/uploaded/profile/profile.png', null=True, upload_to='static/uploaded/profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreOrderModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.TextField()),
                ('nama', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('jenis_furniture', models.TextField()),
                ('picture', models.FileField(null=True, upload_to='static/uploaded/preorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('total_furnitur', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('bukti_pembayaran', models.FileField(upload_to='static/uploaded/payment')),
                ('keranjang_deleted_id', models.IntegerField()),
                ('tanggal_bayar', models.DateTimeField(auto_now_add=True, null=True)),
                ('tanggal_selesai', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('total', models.IntegerField(default=0)),
                ('keranjang_deleted_id', models.IntegerField(default=None, null=True)),
                ('furnitur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.furnituremodels')),
                ('keranjang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.shoppingcartmodels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplainModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.TextField()),
                ('nama', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('deskripsi', models.TextField()),
                ('picture', models.FileField(null=True, upload_to='static/uploaded/complain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatTopicModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatContentModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.chattopicmodels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
